<a href="https://colab.research.google.com/github/usamabaig1/Attribution_Modeling/blob/attributionModeller/Attribution_Modelling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install torch

In [22]:
import torch
import torch.nn as nn
import math

In [29]:
target = torch.randn(1, 5)
target
nn.Linear( 2)

tensor([[-1.1169, -0.5487,  1.2370, -1.4270,  0.6613]])

In [19]:
def my_loss(output, target):
    loss = torch.mean((output - target)**2)
    return loss

model = nn.Linear(2, 2)
x = torch.randn(1, 2)
target = torch.randn(1, 2)
print (target)

for i in range(0,100):
  output = model(x)
  loss = my_loss(output, target)
  loss.backward()
  print(model.weight.grad)
  print(output)
  print("""------------------""")

TypeError: ignored

In [7]:
linear = nn.Linear(32,32)
linear.eval()
N = 10000
X = torch.Tensor(N,32)
X
X.uniform_(0.,1.) # fill with uniform
eps = torch.Tensor(N,32)
eps.normal_(0., 1e-4)

tensor([[ 3.2677e-04, -8.5151e-05,  8.8565e-05,  ...,  1.8070e-05,
         -1.3338e-04,  1.0421e-04],
        [ 6.6139e-05, -6.7598e-05,  1.2029e-04,  ..., -4.9602e-05,
         -1.0679e-04, -1.4397e-05],
        [-1.6079e-06,  4.5771e-05,  9.1935e-06,  ..., -5.7660e-05,
          4.2277e-05, -1.2497e-04],
        ...,
        [ 1.0018e-04,  8.6189e-05,  9.1666e-05,  ...,  1.4094e-04,
         -6.0664e-06, -5.1858e-05],
        [-6.6125e-05, -2.0828e-05, -1.2292e-04,  ..., -1.0999e-05,
         -1.0814e-04, -2.2227e-05],
        [-8.3657e-05, -1.0671e-04, -8.0610e-05,  ...,  3.6681e-05,
         -7.1518e-05, -6.3484e-05]])

In [10]:
torch.randn(3, 2)


tensor([[ 0.1750,  0.1834],
        [-0.9367,  0.0185],
        [ 0.6374, -0.1721]])

In [ ]:
linear = nn.Linear(32,32)
linear = linear.eval()

# input X
N = 10000
X = torch.Tensor(N,32)
X.uniform_(0.,1.) # fill with uniform
eps = torch.Tensor(N,32)
eps.normal_(0., 1e-4)

# output Y
with torch.no_grad():
    Y = linear(X) #+ eps

# make module executing the experiment
class Objective(nn.Module):
    def __init__(self):
        super(Objective, self).__init__()
        self.linear = nn.Linear(32,32)
        self.linear = self.linear.train()
        self.X, self.Y = X, Y

    def forward(self):
        output = self.linear(self.X)
        return F.mse_loss(output, self.Y).mean()

objective = Objective()

maxiter = 100
with tqdm(total=maxiter) as pbar:
    def verbose(xk):
        pbar.update(1)
    # try to optimize that function with scipy
    obj = PyTorchObjective(objective)
    xL = optimize.minimize(obj.fun, obj.x0, method='BFGS', jac=obj.jac,
            callback=verbose, options={'gtol': 1e-6, 'disp': True,
                'maxiter':maxiter})
    #xL = optimize.minimize(obj.fun, obj.x0, method='CG', jac=obj.jac)# , options={'gtol': 1e-2})